-- we can read Lua syntax here!
return {
    ["font_size"] = 18.5,
    ["copt_status_line"] = 1,
    ["copt_rotation_mode"] = 0,
    ["font_hinting"] = 2,
    ["font_kerning"] = 3,
    ["highlight_disabled"] = false,
    ["text_lang_embedded_langs"] = true,
    ["hyphenation"] = true,
    ["hyph_trust_soft_hyphens"] = false,
    ["hyph_soft_hyphens_only"] = false,
    ["hyph_force_algorithmic"] = false,
    ["floating_punctuation"] = 0,
    ["embedded_fonts"] = true,
    ["smooth_scaling"] = false,
    ["percent_finished"] = 1,
    ["nightmode_images"] = true,
    ["cre_dom_version"] = 20200824,
    ["last_xpointer"] = "/body/DocFragment[18]/body/section/p[261]/text().97",
    ["visible_pages"] = 1,
    ["line_space_percent"] = 100,
    ["copt_visible_pages"] = 1,
    ["cache_file_path"] = "./made/up/cache.cr3",
    ["hide_nonlinear_flows"] = false,
    ["inverse_reading_order"] = false,
    ["gamma_index"] = 15,
    ["toc_ticks_ignored_levels"] = {},
    ["copt_embedded_fonts"] = 1,
    ["copt_embedded_css"] = 1,
    ["copt_render_dpi"] = 96,
    ["copt_t_page_margin"] = 15,
    ["highlight"] = {
        [67] = {
            [1] = {
                ["text"] = "Fox is a cunning creature with a warm heart.",
                ["datetime"] = "2021-01-02 12:00:00",
                ["pos0"] = "/body/DocFragment[10]/body/section/p[18]/text()[1].111",
                ["pos1"] = "/body/DocFragment[10]/body/section/p[18]/text()[1].472",
                ["drawer"] = "lighten",
                ["chapter"] = "1. About Fox",
            },
        },
        [235] = {
            [1] = {
                ["pos1"] = "/body/DocFragment[16]/body/section/p[38]/text().942",
                ["datetime"] = "2021-01-01 12:00:00",
                ["pos0"] = "/body/DocFragment[16]/body/section/p[38]/text().646",
                ["text"] = "I got to know Fox in the summer of 1984.",
                ["drawer"] = "lighten",
                ["chapter"] = "0. Preface",
            },
        },
    },
    ["embedded_css"] = true,
    ["readermenu_tab_index"] = 5,
    ["disable_fuzzy_search"] = false,
    ["copt_b_page_margin"] = 15,
    ["copt_sync_t_b_page_margins"] = 0,
    ["copt_smooth_scaling"] = 0,
    ["render_dpi"] = 96,
    ["gamma"] = 1,
    ["partial_md5_checksum"] = "xxxxx",
    ["show_overlap_enable"] = false,
    ["header_font_face"] = "Noto Sans",
    ["copt_font_size"] = 18.5,
    ["copt_font_base_weight"] = 0,
    ["page_overlap_style"] = "dim",
    ["copt_font_kerning"] = 3,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["copt_word_expansion"] = 0,
    ["copt_line_spacing"] = 100,
    ["copt_font_gamma"] = 15,
    ["word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["render_mode"] = 0,
    ["copt_view_mode"] = 0,
    ["preferred_dictionaries"] = {},
    ["config_panel_index"] = 3,
    ["copt_nightmode_images"] = 1,
    ["text_lang"] = "en-US",
    ["word_expansion"] = 0,
    ["rotation_mode"] = 0,
    ["copt_h_page_margins"] = {
        [1] = 10,
        [2] = 10,
    },
    ["copt_font_hinting"] = 2,
    ["doc_props"] = {
        ["description"] = "",
        ["language"] = "en-US",
        ["title"] = "Fox: A Tail",
        ["keywords"] = "",
        ["authors"] = "Jonty Nadem\
Fuzzball Korb",
        ["series"] = "",
    },
    ["stats"] = {
        ["pages"] = 286,
        ["language"] = "en-US",
        ["md5"] = "xxxxx",
        ["notes"] = 0,
        ["title"] = "Fox: A Tail",
        ["highlights"] = 82,
        ["authors"] = "Jonty Nadem\
        Fuzzball Korb",
        ["series"] = "N/A",
    },
    ["bookmarks_sorted"] = true,
    ["doc_pages"] = 286,
    ["copt_block_rendering_mode"] = 3,
    ["highlights_imported"] = true,
    ["css"] = "./data/epub.css",
    ["highlight_drawer"] = "lighten",
    ["font_base_weight"] = 0,
    ["font_face"] = "Noto Serif",
}
